---
.travis.yml:
  acceptance:
    - '*'
  forge_password: "XAv4O363tng0KuRnu1ZhhwORy+2CF9UQwdwlFmS+NG9jOaTZZN+PMK8iC7OSIvZN6cfKlYjHRHNuxFBnYlnMrLsM9fVxt4NjjznOgIKQpQDleWk4UitZj5ntyHmUtYtofUd5Bhi/sdYXwGN9pVRCrcfFBmsIRq/dOhXD7Wy5KcQ="
  allow_failures:
  # Exim is not properly stopped on these OSes, which makes the run non
  # idempotent
  - rvm: default
    sudo: required
    dist: trusty
    services: docker
    env: BEAKER_set="debian-6"
    bundler_args:
    script: sudo service docker restart ; sleep 10 && bundle exec rspec spec/acceptance/*_spec.rb
  - rvm: default
    sudo: required
    dist: trusty
    services: docker
    env: BEAKER_set="debian-7"
    bundler_args:
    script: sudo service docker restart ; sleep 10 && bundle exec rspec spec/acceptance/*_spec.rb

